### ISSUE TITLE
"'NoneType' object is not subscriptable" upon trying to login

### ISSUE THREAD

**Issue by shmedd** [antoinebou12/marketwatch#139] opened 2024-01-26 20:14 UTC
Every attempt to use the MarketWatch tools immediately runs into an error, starting with the log in step.
I have made sure the email and password variables are correct, and are not linked to a google-account-profile.

![image](https://github.com/antoinebou12/marketwatch/assets/79935404/ee7a42b4-587b-42b3-bc10-013bdd5b2a51)
![image](https://github.com/antoinebou12/marketwatch/assets/79935404/82e072a6-de76-4c89-9691-0794edecddcf)

**Comment by antoinebou12** [comment] 2024-01-26 20:16
Ok i will look into it

**Comment by antoinebou12** [comment] 2024-01-26 20:34
Go to this page and try to login with the email and password

https://sso.accounts.dowjones.com/login-page?op=localop&scope=openid%20idp_id%20roles%20email%20given_name%20family_name%20djid%20djUsername%20djStatus%20trackid%20tags%20prts%20updated_at%20createTimestamp&client_id=5hssEAdMy0mJTICnJNvC9TXEw3Va7jfO&response_type=code&redirect_uri=https%3A%2F%2Faccounts.marketwatch.com%2Fauth%2Fsso%2Flogin&nonce=c37db1fb-7cfd-4b20-91d8-39fe90758af1&ui_locales=en-us-x-mw-223-2&ns=prod%2Faccounts-mw&state=cDOnyJN9ISzz7XND.xXrC9IwCnYJhM-VHShckAswvzhYOKp7OhXqoNLhntMM&resource=https%253A%252F%252Fwww.marketwatch.com%252F&protocol=oauth2&client=5hssEAdMy0mJTICnJNvC9TXEw3Va7jfO#!/signin


Then Go to this page and go check your email and password

https://customercenter.marketwatch.com/account?mod=mh_sidebar
![Screenshot_2024-01-26_15-22-39](https://github.com/antoinebou12/marketwatch/assets/13888068/896314e4-932a-4513-a290-f7d3531e21a7)


Try replacing the os with the credentials in python
```
from marketwatch import MarketWatch
marketwatch = MarketWatch("Shmed@gmail.com", "password1234")
```

If there a error 
![Screenshot_2024-01-26_15-29-50](https://github.com/antoinebou12/marketwatch/assets/13888068/0dd62f96-8064-4f07-bf12-4f1c1a5b810b)



I personally use linux so i cannot test on windows http requests. It looks like that the ssl library and auth on windows is differents 

The error is here but i need to test more the code
```
   def login(self):
        """
        Login to the MarketWatch API

        :return: None
        """

        # https://sso.accounts.dowjones.com/authorize?response_type=id_token&nonce=foobar&ui_locales=en-us-x-wsj-3-0&scope=email%2Cfirst_name%2Clast_name%2Croles%2Copenid%2Cuuid&client_id=5hssEAdMy0mJTICnJNvC9TXEw3Va7jfO&redirect_uri=${CALLBACK_URI}
        login_data = {
            "client_id": self.client_id,
            "connection": "DJldap",
            "headers": {
                "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36",
                "Accept": "application/json, text/plain, */*",
                "Accept-Language": "en-US,en;q=0.5",
                "Accept-Encoding": "gzip, deflate, br",
                "Content-Type": "application/json;charset=utf-8",
                "Origin": "https://accounts.marketwatch.com",
                "Connection": "keep-alive",
                "Referer": "https://accounts.marketwatch.com/login-page/signin",
                "TE": "Trailers",
                "X-REMOTE-USER": self.email,
                "x-_dj-_client__id": self.client_id,
                "x-_oidc-_provider": "localop",
            },
            "nonce": "0590aaf2-c662-4fc4-9edc-81727f80798c",
            "ns": "prod/accounts-mw",
            "password": self.password,
            "protocol": "oauth2",
            "redirect_uri": "https://accounts.marketwatch.com/login-page/callback",
            "response_type": "code",
            "scope": "openid idp_id roles email given_name family_name djid djUsername djStatus trackid tags prts suuid updated_at",
            "tenant": "sso",
            "username": self.email,
            "ui_locales": "en-us-x-mw-11-8",
            "_csrf": self.generate_csrf_token(),
            "_intstate": "deprecated",
        }
```

**Comment by antoinebou12** [comment] 2024-01-26 21:55
@shmedd, I've just pushed a new version of the library and am currently conducting tests on Windows. Everything appears to be functioning correctly.

You can view the test results here: [GitHub Actions Run](https://github.com/antoinebou12/marketwatch/actions/runs/7673789251/job/20917140221)

It's possible that the issue you're encountering is due to missing packages in your Python environment. Could you please generate a list of your installed packages? You can do this by running the following command:

bash
Copy code
pip freeze > pip.txt
This will create a file named pip.txt in your current directory, containing a list of all installed Python packages. Please share this file so I can help troubleshoot the issue further.

**Comment by antoinebou12** [comment] 2024-01-27 22:51
Nothing looks wrong here in the pip package. 

ConnectionResetError (WinError 10054): This error occurs when a TCP/IP connection is forcibly closed by the server or an intermediary (like a firewall). In your case, this happens during an SSL handshake, indicating a possible issue with the server accepting the connection or a network-level blockage.

Probable Causes:

The server at sso.accounts.dowjones.com forcibly closes the connection, possibly due to security settings, SSL/TLS version mismatches, or unrecognized client headers.
Network-level issues such as firewalls or antivirus software blocking the connection.
Issues with the Python environment or the httpx and ssl modules, though this is less likely given the nature of the error.

I cannot reproduce this issue in my windows and linux and automatic tests environments.

I trying to fix in this branch : https://github.com/antoinebou12/marketwatch/pull/142

Note: try to reinstall python3 on your windows machine from the windows store

**Comment by antoinebou12** [comment] 2024-02-03 22:21
I have merge damn the changes in new releases @shmedd. If that doesn't work please give me more information on how you install python or virtual env

**Comment by antoinebou12** [comment] 2024-02-04 18:41
> Downloading the latest release solved all my issues. Thank you so much!

If you need help in your projects please tell me or you need another feature. 

Thanks you 😊

**Closed** 2024-02-04 18:42 UTC
Labels: bug
